# Model:
model_name: <need specify ./model_you_want_to_use>
load_entire_agent: false
reshaper_type: learned
two_ffwd: false
unit_norm: false
dropout: 0.0
share_reshaper: true
image_unroll: recurrent
image_unroll_length: 32
recurrent_hidden_aggregation: <need specify -- true or false>
freeze_adapters: false
freeze_sender: false
freeze_receiver: false
