# Model:
model_name: ./model_you_want_to_use
load_entire_agent: true
image_dim: 2048
reshaper_type: learned
two_ffwd: false
unit_norm: false
dropout: 0.0
share_reshaper: true
image_unroll: lstm
image_unroll_length: 32
recurrent_hidden_aggregation: false
freeze_adapters: false
freeze_sender: false
freeze_receiver: false