# training config
num_steps: 2048
lr: 1.0e-5
grad_clip: 1.0
num_warmup_steps: 256
schedule: constant_w_warmup
batch_size: 32
seed: 1
n_gpu: 1
print_every: 32
do_initial_eval: false
do_crossent_eval: false
eval_every: 128
crossent_patience: 16
do_translate_eval: true
translate_every: 256
validation_set_size: 4096
eval_batch_size: 64
num_beams: 5
val_metric_name: bleu
num_constrained_steps: 2048
vocab_constraint_threshold: 0.96
secondary_threshold: 0.99
early_stop_start_time: ${.num_steps}

# script to load validation datasets
models_shared: true

print_translation: false # Whether we want to print backtranslated sentence, for inspection
num_printed_translation: 3 # Number of backtranslated sentences to print

