# Path to load model for generation
model_path: Output/en-zh_tec/ec

# training config
num_steps: 8192
lr: 1.0e-05
grad_clip: 1.0
num_warmup_steps: 1024
schedule: constant_w_warmup
batch_size: 32
seed: 1
n_gpu: 1
num_beams: 5
print_every: 32
do_initial_eval: false
do_crossent_eval: false
eval_every: 128
crossent_patience: 16
do_translate_eval: true
translate_every: 256
validation_set_size: 4096
eval_batch_size: 64
val_metric_name: bleu
num_constrained_steps: 2048
vocab_constraint_threshold: 0.96
secondary_threshold: 0.99
early_stop_start_time: 8192

# script to load validation datasets
val_dataset_script: BackTranslation/wmt19/wmt19.py
lang_pair: zh-en
models_shared: true
output_dir: Output/en-zh_tec/bt

# data config
data_dir: ./DataLink/cc
output_data_filename: bt_en+zh.csv
lang1_data_file: en_500k.txt
lang1_id: en
lang1_max_len: 64
lang1_vocab_constrain_file: ./Data/cc/en_cc_tokenID2count_dict.cc25.json

lang2_data_file: zh_500k.txt
lang2_id: zh
lang2_max_len: 64
lang2_vocab_constrain_file: ./Data/cc/zh_cc_tokenID2count_dict.cc25.json
