# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: zh-en.en.test.zh

output_dir: ./Output/en-zh_tec/translation_results
model_path: ./Output/en-zh_tec/bt/best_bleu

# data config
source_data_file: ./Data/translation_references/zh-en.en.test
source_id: en
source_max_len: 64
target_id: zh
target_max_len: 64
