# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: si-en.en.test.si

output_dir: ./Output/en-si_tec/translation_results
model_path: ./Output/en-si_tec/bt/best_bleu

# data config
source_data_file: ./Data/translation_references/si-en.en.test
source_id: en
source_max_len: 64
target_id: si
target_max_len: 64
