# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: zh-en.en.test.zh

# data config
source_data_file: Output/translation_references/zh-en.en.test
lang_pair: zh-en
dataset_split: test
source_id: zh
source_max_len: 64
target_id: zh
target_max_len: 64
