# Hyper-parameters for the referential games 
D_emb: 1024
D_hid: 512
D_img: 2048
ECemb: 5000
TransferH: false
alpha: 1.0
bart: true
batch_size: 2
beam_width: 12
cpu: false
dataset: coco
decode_how: beam
dropout: 0.1
eval_mode: false
fix_bhd: false
fix_spk: false
gpuid: 0
grad_clip: 1.0
hard: false
len_loss: false
loss_type: xent
lr: 1.0e-05
no_share_bhd: false
no_terminal: false
no_write: false
norm_pow: 0.0
num_directions: 1
num_dist: 256
num_dist_: 128
num_games: 30000
num_layers: 1
pretrain_spk: false
print_every: 50
re_load: false
sample_how: gumbel
save_every: 4000
seq_len: 15
stop_after: 30
temp: 1.0
translate_every: 2000
two_fc: false
unit_norm: false
valid_batch_size: 128
valid_every: 250
vocab_size: 4035
which_loss: joint
# specify info about language and vocab constraint
lang_1: en_XX
lang_1_vocab_constrain_file: ../UMT_data/cc/en_europarl_count_dict.json
lang_2: ja_XX
lang_2_vocab_constrain_file: ../UMT_data/cc/ja_smaller_count_dict.json
