defaults:
  - data: en-de
  - train: train_secondary
  - validation: valid
  - _self_

validation:
  output_dir: ./Output/en-de_pipeline/bt_sec
  lang_pair: de-en

# # script to load validation datasets
# val_dataset_script: BackTranslation/wmt19/wmt19.py
# lang_pair: de-en # what's the difference between de-en and en-de?
# models_shared: true
# output_dir: ./Output/en-de_pipeline/bt_sec