# Model:
model_name: temp/Output/en-de_pipeline_debug/bt_init/last
load_entire_agent: false
image_dim: 512
reshaper_type: learned
two_ffwd: false
unit_norm: false
dropout: 0.0
share_reshaper: false
recurrent_image_unroll: true
image_unroll_length: 32
recurrent_hidden_aggregation: false
freeze_adapters: false
freeze_sender: false
freeze_receiver: false
freeze_img_encoder: true

# Raw image process:
input_sequence: false
input_image: false # turning this to false would disable all the variables below it in this chunk
sender_image_dim: 512 # Image embedding dim directly from image encoder
do_transform: true
downsample: linear
img_encode_model: clip
read_img_folder: false
raw_image_dir: ../vision_feats/train2014
train_img_name_file: ./Data/beit_ft_captioning/train_image_names.txt
val_img_name_file: ./Data/beit_ft_captioning/val_image_names.txt

# Generation
beam_width: 1
temperature: 1.0
hard: true
max_seq_length: 32
repetition_penalty: 1.0
generate_from_logits: false
TransferH: false # switch to hard gumbel after the model reaches target accuracy

# Train and eval:
seed: 1
mode: image_grounding
image_selection_lambda: 5.0
language_model_lambda: 0.0
weight_drift_lambda: 0.0
do_train: true
do_eval: true
n_gpu: 1
num_games: 30 # Upper bound of the num of epochs
max_global_step: 2048
lr: 4.0e-5
schedule: linear_w_warmup
num_warmup_steps: 0
gradient_accumulation_steps: 1
batch_size: 16
grad_clip: 1.0
valid_every: 512
print_every: 32
target_acc: 85.0
stats_to_print: ['loss', 'accuracy', 'caption generation loss', 'image selection loss']

# Number of image distractors
num_distractors_train: 15
num_distractors_valid: 15

# Loading and saving data:
train_captions: ./Data/captioning_new_new/en_captions_train.jsonl
valid_captions: ./Data/captioning_new_new/en_captions_val.jsonl
train_images: ./Data/captioning_new_new/clip_train.pt
valid_images: ./Data/captioning_new_new/clip_val.pt
save_pretrain_seperately: true
output_dir: Output/en-de_pipeline/captions_vision_clip
save_output_txt: true

# Specify info about language and vocab constraint
has_vocab_constraint: false
source_lang: en_XX
source_lang_vocab_constrain_file: /projects/unmt/communication-translation/en_cc_tokenID2count_dict.cc25.json
