# Path to load model for generation
model_path: facebook/mbart-large-cc25

# training config
num_steps: 8192
lr: 2.0e-05
grad_clip: 1.0
num_warmup_steps: 1024
schedule: constant_w_warmup
batch_size: 32
seed: 1
n_gpu: 1
num_beams: 5
print_every: 32
do_initial_eval: false
do_crossent_eval: false
eval_every: 128
crossent_patience: 16
do_translate_eval: true
translate_every: 256
validation_set_size: 4096
eval_batch_size: 64
val_metric_name: bleu
num_constrained_steps: 2048
vocab_constraint_threshold: 0.90
secondary_threshold: 0.99
early_stop_start_time: 8192