# Specify info about language and vocab constraint
has_vocab_constraint: true
source_lang: en_XX
source_lang_vocab_constrain_file: ./Data/cc/en_cc_tokenID2count_dict.cc25.json
target_lang: si_LK
target_lang_vocab_constrain_file: ./Data/cc/si_cc_tokenID2count_dict.facebook-mbart-large-cc25.json
