# Specify info about language and vocab constraint
has_vocab_constraint: true
source_lang: en_XX
source_lang_vocab_constrain_file: ./Data/cc/en_cc_tokenID2count_dict.cc25.json
target_lang: zh_CN
target_lang_vocab_constrain_file: ./Data/cc/zh_cc_tokenID2count_dict.cc25.json