# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: de-en.de.val.en

# data config
source_data_file: Output/en-de_pipeline/de-en.de.val
source_id: de
source_max_len: 64
target_id: en
target_max_len: 64
