# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: de-en.en.test.de

# data config
source_data_file: Data/translation_references/de-en.en.test
lang_pair: de-en
dataset_split: test
source_id: en
source_max_len: 64
target_id: de
target_max_len: 64
