# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: neen.en.val.ne

# data config
dataset_script: BackTranslation/flores/flores.py
lang_pair: neen
dataset_split: val
source_id: en
source_max_len: 64
target_id: ne
target_max_len: 64
