# Path to load model for generation
model_path: Output/en-zh_pipeline/bt_init/last
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
output_dir: Output/en-zh_pipeline/
translation_filename: zh-en.en.val.zh

# data config
dataset_script: BackTranslation/wmt19/wmt19.py
lang_pair: zh-en
dataset_split: validation
source_id: en
source_max_len: 64
target_id: zh
target_max_len: 64
