# Hyper-parameters for the referential games 

# Model: 
model: bart
bart: true
batch_size: 16
embedding_dim: 1024
hidden_dim: 512
image_dim: 2048
bidirectional: false # RNN-specific
num_layers: 1 #RNN-specific 
vocab_size: 4035 #RNN-specific

# Training: 
seed: 42
TransferH: false #switch to hard gumbel after the model reaches target accuracy.
# Setting the n_gpu we use
n_gpu: 1
cpu: False
dataset: coco
coco_path: Data/coco_new
#coco_path: /gscratch/ark/xuhuizh/UMT_data/coco_new # Keep this for the conv
#of my local dev.
dropout: 0.1
eval_mode: false
fix_bhd: false
fix_spk: false
gpuid: 0
grad_clip: 1.0
hard: true # We always prefer to set this true
len_loss: false
loss_type: xent
lr: 1.0e-05
no_share_bhd: false
no_terminal: false
no_write: false
norm_pow: 0.0
num_distractors_train: 255
num_distractors_valid: 127
num_games: 30000
pretrain_spk: false
print_every: 50
re_load: false
sample_how: gumbel
save_every: 4000
seq_len: 15
stop_after: 30
temp: 1.0
translate_every: 2000
two_ffwd: false
unit_norm: false
valid_batch_size: 128
valid_every: 250
which_loss: joint

# Model saving parameters
save_pretrain_seperately: true
output_dir: Output
results_save_path: Output

# Other unimportant parameters:
alpha: 1.0
beam_width: 12
decode_how: beam
