# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: sien.si.test.en

output_dir: Output/en-si_pipeline
model_path: Output/en-si_pipeline/best_bleu

# data config
source_data_file: sien.si.test
source_id: si
source_max_len: 64
target_id: en
target_max_len: 64
