# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: neen.en.test.ne

output_dir: Output/en-ne_pipeline
model_path: Output/en-ne_pipeline/best_bleu

# data config
source_data_file: sien.ne.test
source_id: en
source_max_len: 64
target_id: ne
target_max_len: 64
