# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: zh-en.en.test.zh

output_dir: Output/en-zh_pipeline
model_path: Output/en-zh_pipeline/best_bleu

# data configs
source_data_file: zh-en.en.test
source_id: en
source_max_len: 64
target_id: zh
target_max_len: 64
