# Path to load model for generation
seed: 1
n_gpu: 1
batch_size: 64
num_beams: 5
translation_filename: de-en.de.test.en

output_dir: ./Output/en-de_pipeline/translation_results
model_path: ./Output/en-de_pipeline/best_bleu

# data config
source_data_file: ./Data/translation_references/de-en.de.test
source_id: de
source_max_len: 64
target_id: en
target_max_len: 64
