defaults:
  - model: base_ec
  - train_eval: base_ec
  - generation: base_ec
  - data: resnet
  - language: en-de
  - _self_

# I2I-specific train and eval configs:
output_dir: ./Output/en-de_pipeline/ec
mode: emergent_communication
save_pretrain_seperately: true

model:
  model_name: ./Output/en-de_pipeline/captions
  recurrent_hidden_aggregation: false

train_eval:
  sender_input: image
  language_model_lambda: 0.125
  lr: 6.0e-6
  grad_clip: 1.0
