defaults:
  - model: base_caption
  - train_eval: base_caption
  - generation: base_caption
  - data: resnet
  - language: en-de
  - _self_

# I2I-specific train and eval configs:
output_dir: ./Output/en-de_pipeline/captions
mode: image_grounding
save_pretrain_seperately: true

model:
  model_name: ./Output/en-de_pipeline/bt_init/last
  recurrent_hidden_aggregation: false

train_eval:
  image_selection_lambda: 4.0
  grad_clip: 1.0

  # Number of image distractors
  num_distractors_train: 15
  num_distractors_valid: 15
  
language:
  has_vocab_constraint: false


