defaults:
  - model: base_ec
  - train_eval: base_ec
  - generation: base_ec
  - data: resnet
  - language: en-ne
  - _self_

# I2I-specific train and eval configs:
output_dir: ./Output/en-de_pipeline/ec
mode: emergent_communication
save_pretrain_seperately: true

data:
  base_dir: ./DataLink/ec_finetuning_new

model:
  model_name: ./Output/en-de_pipeline/captions
  # in preprint, we have recurrent_hidden_aggregation: false. '
  # But according to Agatha, setting to True is important (at least for T2I). 
  
train_eval:
  sender_input_type: image
  language_model_lambda: 0.125
  lr: 6.0e-6
  grad_clip: 1.0
