defaults:
  - model: base_caption
  - train_eval: base_caption
  - generation: base_caption
  - data: resnet
  - language: en-ne
  - _self_

# T2I-specific train and eval configs:
output_dir: ./Output/en-ne_pipeline/captions
mode: image_grounding
save_pretrain_seperately: true

data:
  base_dir: ./DataLink/captioning_new_new

model:
  model_name: facebook/mbart-large-cc25
  recurrent_hidden_aggregation: false

train_eval:
  sender_input_type: image

language:
  has_vocab_constraint: false


