defaults:
  - model: base_caption
  - train_eval: base_caption
  - generation: base_caption
  - data: resnet
  - language: en-de
  - _self_

# T2I-specific train and eval configs:
output_dir: ./Output/en-de_pipeline/captions
mode: image_grounding
save_pretrain_seperately: true

model:
  model_name: facebook/mbart-large-cc25
  recurrent_hidden_aggregation: true
  
train_eval:
  image_selection_lambda: 4.0
  grad_clip: 1.0

  # Number of image distractors
  num_distractors_train: 15
  num_distractors_valid: 15
  # image_selection_lambda: 8.0
  # grad_clip: 0.5

  # # Number of image distractors
  # num_distractors_train: 7
  # num_distractors_valid: 7

generation:
  max_text_seq_length: 128

language:
  has_vocab_constraint: false


